{
  config,
  lib,
  ...
}:

let
  cfg = config.doomemacs;
in
{
  config = lib.mkIf (cfg.enable && cfg.features.cursor) {
    doomemacs.generatedLisp."+cursor.el" = ''
      ;;; +cursor.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake.
      ;; Cursor IDE + Cursor CLI Agent integration.

      (defconst +cursor-local-bin (expand-file-name "~/.local/bin")
        "User-local bin directory used by the Cursor CLI Agent installer.")

      (defun +cursor--ensure-local-bin-on-path ()
        "Put ~/.local/bin on `exec-path' and PATH so `agent' is found."
        (when (file-directory-p +cursor-local-bin)
          (add-to-list 'exec-path +cursor-local-bin)
          (let ((path (getenv "PATH")))
            (unless (and path (string-match-p (regexp-quote +cursor-local-bin) path))
              (setenv "PATH" (concat +cursor-local-bin path-separator (or path "")))))))

      (+cursor--ensure-local-bin-on-path)

      (defun +cursor/open-in-ide (&optional path)
        "Open PATH (file, directory, or current project) in the Cursor IDE.
      With a prefix argument, always open the project root."
        (interactive
         (list (if current-prefix-arg
                   (or (doom-project-root) default-directory)
                 (or (buffer-file-name)
                     (doom-project-root)
                     default-directory))))
        (let ((cursor (or (executable-find "cursor")
                          (executable-find "cursor-agent")))
              (target (expand-file-name (or path default-directory))))
          (unless cursor
            (user-error "Cursor executable not found on PATH"))
          (start-process "cursor-ide" nil cursor target)
          (message "Opened in Cursor: %s" target)))

      (defun +cursor/open-project-in-ide ()
        "Open the current project root in the Cursor IDE."
        (interactive)
        (+cursor/open-in-ide (or (doom-project-root) default-directory)))

      (use-package! cursor-agent
        :commands (cursor-agent-prompt
                   cursor-agent-interactive
                   cursor-agent-region
                   cursor-agent-resume
                   cursor-agent-list-sessions
                   cursor-agent-list-models
                   cursor-agent-mcp-list
                   cursor-agent-shell-mode
                   cursor-agent-install
                   cursor-agent-update
                   cursor-agent-login
                   cursor-agent-status
                   cursor-agent-verify-setup)
        :init
        (+cursor--ensure-local-bin-on-path)
        :config
        (+cursor--ensure-local-bin-on-path)
        (setq cursor-agent-command (or (and (executable-find "agent") "agent")
                                       (and (executable-find "cursor-agent") "cursor-agent")
                                       "agent")
              cursor-agent-default-output-format "text"
              cursor-agent-use-force nil))

      (map! :leader
            (:prefix "c"
             (:prefix ("A" . "cursor-agent")
              :desc "Prompt" "a" #'cursor-agent-prompt
              :desc "Interactive session" "i" #'cursor-agent-interactive
              :desc "Process region" "r" #'cursor-agent-region
              :desc "Resume session" "R" #'cursor-agent-resume
              :desc "List sessions" "l" #'cursor-agent-list-sessions
              :desc "List models" "m" #'cursor-agent-list-models
              :desc "MCP servers" "M" #'cursor-agent-mcp-list
              :desc "Shell mode" "S" #'cursor-agent-shell-mode
              :desc "Install CLI" "I" #'cursor-agent-install
              :desc "Update CLI" "u" #'cursor-agent-update
              :desc "Login" "L" #'cursor-agent-login
              :desc "Status" "s" #'cursor-agent-status
              :desc "Verify setup" "v" #'cursor-agent-verify-setup
              :desc "Open in Cursor IDE" "o" #'+cursor/open-in-ide
              :desc "Open project in Cursor" "O" #'+cursor/open-project-in-ide)))

      ${cfg.cursor.extraConfig}
    '';
  };
}
