{
  config,
  lib,
  ...
}:

let
  cfg = config.doomemacs;
in
{
  config = lib.mkIf (cfg.enable && cfg.features.editor) {
    doomemacs.generatedLisp."+editor.el" = ''
      ;;; +editor.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake.

      (setq shell-file-name (or (executable-find "bash") "/usr/bin/bash"))
      ${
        if cfg.editor.vtermShell != null then
          ''
            (setq-default vterm-shell "${cfg.editor.vtermShell}"
                          explicit-shell-file-name "${cfg.editor.vtermShell}")
          ''
        else
          ''
            (let ((nu (or (executable-find "nu") "/run/current-system/sw/bin/nu")))
              (setq-default vterm-shell nu
                            explicit-shell-file-name nu))
          ''
      }

      ${lib.optionalString cfg.editor.caseSensitiveSearch ''
        (setq-default case-fold-search nil)
        (after! evil
          (setq evil-ex-search-case 'sensitive))
      ''}

      (after! consult
        (setq consult-ripgrep-args
              (concat "rg -U --null --line-buffered --color=never "
                      "--max-columns=1000 --path-separator / "
                      "--smart-case --no-heading --line-number .")))

      (use-package! javelin
        :config
        (global-javelin-minor-mode 1))

      (use-package! nushell-ts-mode
        :mode "\\.nu\\'")

      (map! :leader
            :desc "Dirvish side" "-" #'dirvish-side
            :desc "Dirvish DWIM" "5" #'dirvish-dwim
            :desc "Dirvish dispatch" "6" #'dirvish-dispatch)

      (after! dired
        (map! :map dired-mode-map
              "+" #'dired-create-empty-file))

      (map! "M-;" #'comment-line
            "M-p" #'yank-from-kill-ring
            "C-w ;" #'ace-select-window)

      (map! :v "R" #'evil-multiedit-match-all
            :nv "M-d" #'evil-multiedit-match-and-next
            :i "M-d" #'evil-multiedit-toggle-marker-here)

      ${cfg.editor.extraConfig}
    '';
  };
}
