{
  config,
  lib,
  ...
}:

let
  cfg = config.doomemacs;
in
{
  config = lib.mkIf (cfg.enable && cfg.features.lsp) {
    doomemacs.generatedLisp."+lsp.el" = ''
      ;;; +lsp.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake.

      ${lib.optionalString cfg.lsp.disableSemgrep ''
        (setq lsp-semgrep-enabled nil
              lsp-disabled-clients '(semgrep-ls))
      ''}
      (setq lsp-diagnostics-provider :${cfg.lsp.diagnosticsProvider})

      (after! lsp-ui
        (setq lsp-ui-doc-enable ${if cfg.lsp.uiDoc.enable then "t" else "nil"}
              lsp-ui-doc-delay ${toString cfg.lsp.uiDoc.delay}
              lsp-ui-doc-max-width ${toString cfg.lsp.uiDoc.maxWidth}
              lsp-ui-sideline-enable t
              lsp-ui-sideline-show-hover t
              lsp-ui-sideline-show-diagnostics t
              lsp-ui-imenu-window-width 30
              lsp-ui-imenu-auto-refresh t
              lsp-ui-peek-enable t))

      ${cfg.lsp.extraConfig}
    '';
  };
}
