{
  config,
  lib,
  ...
}:

let
  cfg = config.doomemacs;
  babelPairs = lib.concatMapStringsSep "\n           " (lang: "(${lang} . t)") cfg.org.babelLanguages;
in
{
  config = lib.mkIf (cfg.enable && cfg.features.org) {
    doomemacs.generatedLisp."+org.el" = ''
      ;;; +org.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake.

      (setq org-directory "${cfg.org.directory}")

      (after! org
        (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
        (org-babel-do-load-languages
         'org-babel-load-languages
         (append org-babel-load-languages
                 '(${babelPairs})))
        (when (locate-library "edraw-org")
          (require 'edraw-org)
          (edraw-org-setup-default)))

      (after! ox
        (when (locate-library "edraw-org")
          (require 'edraw-org)
          (edraw-org-setup-exporter)))

      (after! rustic
        (require 'rustic-babel))

      ${lib.optionalString cfg.org.roamUi ''
        (use-package! org-roam-ui
          :after org-roam
          :commands (org-roam-ui-mode org-roam-ui-open)
          :config
          (setq org-roam-ui-sync-theme t
                org-roam-ui-follow t
                org-roam-ui-update-on-save t
                org-roam-ui-open-on-start nil))
      ''}

      ${cfg.org.extraConfig}
    '';
  };
}
