{
  config,
  lib,
  ...
}:

let
  cfg = config.doomemacs;
  elisp = import ../../lib/elisp.nix { inherit lib; };
in
{
  config = lib.mkIf (cfg.enable && cfg.features.ui) {
    doomemacs.generatedLisp."+ui.el" = ''
      ;;; +ui.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake.

      (setq doom-font ${
        elisp.fontSpec {
          inherit (cfg.ui.font) family size weight;
        }
      }
            doom-variable-pitch-font ${
              elisp.fontSpec {
                inherit (cfg.ui.variablePitchFont) family size;
              }
            }
            doom-theme '${cfg.ui.theme}
            display-line-numbers-type ${elisp.lineNumbersEl cfg.ui.lineNumbers}
            message-log-max t)

      ${cfg.ui.extraConfig}
    '';
  };
}
