{ lib }:

let
  inherit (lib)
    concatMapStringsSep
    concatStringsSep
    filterAttrs
    mapAttrsToList
    optionalString
    replaceStrings
    ;

  escape = replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ];

  categoryOrder = [
    "input"
    "completion"
    "ui"
    "editor"
    "emacs"
    "term"
    "checkers"
    "tools"
    "os"
    "lang"
    "email"
    "app"
    "config"
  ];

  isEnabled = spec: spec.enable or true;

  formatFlags = flags: concatStringsSep " " (map (f: "+${f}") flags);

  formatModule =
    name: spec:
    let
      flags = spec.flags or [ ];
      body = if flags == [ ] then name else "(${name} ${formatFlags flags})";
      when = spec.when or null;
    in
    if when == null then "       ${body}" else "       (:if ${when} ${body})";

  formatCategory =
    cat: modules:
    let
      enabled = filterAttrs (_: isEnabled) modules;
      lines = mapAttrsToList formatModule enabled;
    in
    optionalString (enabled != { }) ''
             :${cat}
      ${concatStringsSep "\n" lines}
    '';

  formatRecipe =
    recipe:
    let
      host = optionalString (recipe.host or null != null) ":host ${recipe.host}";
      repo = optionalString (recipe.repo or null != null) ":repo \"${escape recipe.repo}\"";
      branch = optionalString (recipe.branch or null != null) ":branch \"${escape recipe.branch}\"";
      pin = optionalString (recipe.pin or null != null) ":pin \"${escape recipe.pin}\"";
      files =
        optionalString (recipe.files or [ ] != [ ])
          ":files (${concatMapStringsSep " " (f: "\"${escape f}\"") recipe.files})";
      extra = recipe.extra or "";
    in
    concatStringsSep " " (
      builtins.filter (s: s != "") [
        host
        repo
        branch
        pin
        files
        extra
      ]
    );

  formatPackage =
    pkg:
    if (pkg.recipe or null) == null && (pkg.unpin or false) == false then
      "(package! ${pkg.name})"
    else if (pkg.recipe or null) == null then
      "(package! ${pkg.name})"
    else
      ''
        (package! ${pkg.name}
          :recipe (${formatRecipe pkg.recipe}))'';

  lineNumbersEl =
    value:
    {
      relative = "'relative";
      visual = "'visual";
      absolute = "t";
      none = "nil";
    }
    .${value};

  weightEl = weight: optionalString (weight != null) " :weight '${weight}";

  fontSpec =
    {
      family,
      size,
      weight ? null,
    }:
    "(font-spec :family \"${escape family}\" :size ${toString size}${weightEl weight})";
in
{
  inherit
    categoryOrder
    escape
    fontSpec
    lineNumbersEl
    ;

  mkInitEl =
    {
      modules,
      extraInit ? "",
    }:
    let
      body = concatStringsSep "\n" (
        builtins.filter (s: s != "") (map (cat: formatCategory cat (modules.${cat} or { })) categoryOrder)
      );
    in
    ''
      ;;; init.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake. Do not edit; change Nix options instead.

      (doom!
      ${body}
      )
      ${extraInit}
    '';

  mkPackagesEl =
    {
      packages,
      extraPackages ? [ ],
      unpin ? [ ],
    }:
    let
      all = packages ++ extraPackages;
    in
    ''
      ;; -*- no-byte-compile: t; -*-
      ;;; $DOOMDIR/packages.el
      ;; Generated by the doomemacs Nix flake. Do not edit; change Nix options instead.

      ${concatMapStringsSep "\n" formatPackage all}
      ${optionalString (unpin != [ ]) "(unpin! ${concatStringsSep " " unpin})"}
    '';

  mkConfigEl =
    {
      loads,
      extraConfigEarly ? "",
      extraConfig ? "",
    }:
    ''
      ;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
      ;; Generated by the doomemacs Nix flake. Do not edit; change Nix options instead.

      ${extraConfigEarly}
      ${concatMapStringsSep "\n" (name: "(load! \"${name}\")") loads}

      ${extraConfig}
    '';
}
